In [1]:
import numpy as np

a = np.arange(9)
print("The Original array:")
print(a)
print()

b = a.reshape(3,3)

print("The modified array: ")
print(b)


The Original array:
[0 1 2 3 4 5 6 7 8]

The modified array: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
print(b.flatten())

[0 1 2 3 4 5 6 7 8]


In [ ]:
a =  np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [2]:
print(b.flatten())


[0 1 2 3 4 5 6 7 8]


In [3]:
print(np.transpose(a))


[0 1 2 3 4 5 6 7 8]


In [6]:
z = np.random.rand(10,10)
z[np.random.randint(10,size  = 5)]=np.nan
z

array([[2.90424185e-01, 4.10579994e-02, 3.12977438e-01, 4.24325148e-01,
        2.76048905e-01, 3.37188966e-01, 5.54623123e-01, 2.40932094e-02,
        3.81036102e-01, 8.42123964e-01],
       [4.92800613e-01, 9.52480565e-01, 4.46819151e-01, 3.90969285e-01,
        1.07549520e-01, 5.39735721e-01, 3.13274502e-01, 3.80471207e-01,
        6.36717207e-01, 8.48085140e-01],
       [           nan,            nan,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan,            nan],
       [5.85460741e-01, 1.86308763e-01, 3.51294196e-01, 5.74932388e-01,
        6.72169147e-01, 9.05230417e-04, 3.22538339e-01, 1.96097191e-01,
        5.75725471e-01, 4.87389695e-01],
       [           nan,            nan,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan,            nan],
       [           nan,            nan,            nan,            nan,
   

In [8]:
print("Total number of missing values: \n", np.isnan(z).sum())
print("Indexes of missing values : \n", np.argwhere(np.isnan(z)))

Total number of missing values: 
 50
Indexes of missing values : 
 [[2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [2 5]
 [2 6]
 [2 7]
 [2 8]
 [2 9]
 [4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]
 [4 5]
 [4 6]
 [4 7]
 [4 8]
 [4 9]
 [5 0]
 [5 1]
 [5 2]
 [5 3]
 [5 4]
 [5 5]
 [5 6]
 [5 7]
 [5 8]
 [5 9]
 [7 0]
 [7 1]
 [7 2]
 [7 3]
 [7 4]
 [7 5]
 [7 6]
 [7 7]
 [7 8]
 [7 9]
 [8 0]
 [8 1]
 [8 2]
 [8 3]
 [8 4]
 [8 5]
 [8 6]
 [8 7]
 [8 8]
 [8 9]]
